### YamlMime:ManagedReference
items:
- uid: RateLimiter.Configuration.RateLimiterOptions
  commentId: T:RateLimiter.Configuration.RateLimiterOptions
  id: RateLimiterOptions
  parent: RateLimiter.Configuration
  children:
  - RateLimiter.Configuration.RateLimiterOptions.FixedWindow
  - RateLimiter.Configuration.RateLimiterOptions.SectionName
  - RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
  - RateLimiter.Configuration.RateLimiterOptions.TokenBucket
  langs:
  - csharp
  - vb
  name: RateLimiterOptions
  nameWithType: RateLimiterOptions
  fullName: RateLimiter.Configuration.RateLimiterOptions
  type: Class
  source:
    remote:
      path: RateLimiter/Configuration/RateLimiterOptions.cs
      branch: cursor/build-xml-and-documentation-with-dotfx-2e95
      repo: https://github.com/todicn/RateLimiterPP
    id: RateLimiterOptions
    path: RateLimiter/Configuration/RateLimiterOptions.cs
    startLine: 5
  assemblies:
  - RateLimiter
  namespace: RateLimiter.Configuration
  summary: Configuration options for rate limiters
  example: []
  syntax:
    content: public class RateLimiterOptions
    content.vb: Public Class RateLimiterOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: RateLimiter.Configuration.RateLimiterOptions.SectionName
  commentId: F:RateLimiter.Configuration.RateLimiterOptions.SectionName
  id: SectionName
  parent: RateLimiter.Configuration.RateLimiterOptions
  langs:
  - csharp
  - vb
  name: SectionName
  nameWithType: RateLimiterOptions.SectionName
  fullName: RateLimiter.Configuration.RateLimiterOptions.SectionName
  type: Field
  source:
    remote:
      path: RateLimiter/Configuration/RateLimiterOptions.cs
      branch: cursor/build-xml-and-documentation-with-dotfx-2e95
      repo: https://github.com/todicn/RateLimiterPP
    id: SectionName
    path: RateLimiter/Configuration/RateLimiterOptions.cs
    startLine: 7
  assemblies:
  - RateLimiter
  namespace: RateLimiter.Configuration
  syntax:
    content: public const string SectionName = "RateLimiter"
    return:
      type: System.String
    content.vb: Public Const SectionName As String = "RateLimiter"
- uid: RateLimiter.Configuration.RateLimiterOptions.TokenBucket
  commentId: P:RateLimiter.Configuration.RateLimiterOptions.TokenBucket
  id: TokenBucket
  parent: RateLimiter.Configuration.RateLimiterOptions
  langs:
  - csharp
  - vb
  name: TokenBucket
  nameWithType: RateLimiterOptions.TokenBucket
  fullName: RateLimiter.Configuration.RateLimiterOptions.TokenBucket
  type: Property
  source:
    remote:
      path: RateLimiter/Configuration/RateLimiterOptions.cs
      branch: cursor/build-xml-and-documentation-with-dotfx-2e95
      repo: https://github.com/todicn/RateLimiterPP
    id: TokenBucket
    path: RateLimiter/Configuration/RateLimiterOptions.cs
    startLine: 12
  assemblies:
  - RateLimiter
  namespace: RateLimiter.Configuration
  summary: Token bucket configuration
  example: []
  syntax:
    content: public TokenBucketOptions TokenBucket { get; set; }
    parameters: []
    return:
      type: RateLimiter.Configuration.TokenBucketOptions
    content.vb: Public Property TokenBucket As TokenBucketOptions
  overload: RateLimiter.Configuration.RateLimiterOptions.TokenBucket*
- uid: RateLimiter.Configuration.RateLimiterOptions.FixedWindow
  commentId: P:RateLimiter.Configuration.RateLimiterOptions.FixedWindow
  id: FixedWindow
  parent: RateLimiter.Configuration.RateLimiterOptions
  langs:
  - csharp
  - vb
  name: FixedWindow
  nameWithType: RateLimiterOptions.FixedWindow
  fullName: RateLimiter.Configuration.RateLimiterOptions.FixedWindow
  type: Property
  source:
    remote:
      path: RateLimiter/Configuration/RateLimiterOptions.cs
      branch: cursor/build-xml-and-documentation-with-dotfx-2e95
      repo: https://github.com/todicn/RateLimiterPP
    id: FixedWindow
    path: RateLimiter/Configuration/RateLimiterOptions.cs
    startLine: 17
  assemblies:
  - RateLimiter
  namespace: RateLimiter.Configuration
  summary: Fixed window configuration
  example: []
  syntax:
    content: public FixedWindowOptions FixedWindow { get; set; }
    parameters: []
    return:
      type: RateLimiter.Configuration.FixedWindowOptions
    content.vb: Public Property FixedWindow As FixedWindowOptions
  overload: RateLimiter.Configuration.RateLimiterOptions.FixedWindow*
- uid: RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
  commentId: P:RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
  id: SlidingWindow
  parent: RateLimiter.Configuration.RateLimiterOptions
  langs:
  - csharp
  - vb
  name: SlidingWindow
  nameWithType: RateLimiterOptions.SlidingWindow
  fullName: RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
  type: Property
  source:
    remote:
      path: RateLimiter/Configuration/RateLimiterOptions.cs
      branch: cursor/build-xml-and-documentation-with-dotfx-2e95
      repo: https://github.com/todicn/RateLimiterPP
    id: SlidingWindow
    path: RateLimiter/Configuration/RateLimiterOptions.cs
    startLine: 22
  assemblies:
  - RateLimiter
  namespace: RateLimiter.Configuration
  summary: Sliding window configuration
  example: []
  syntax:
    content: public SlidingWindowOptions SlidingWindow { get; set; }
    parameters: []
    return:
      type: RateLimiter.Configuration.SlidingWindowOptions
    content.vb: Public Property SlidingWindow As SlidingWindowOptions
  overload: RateLimiter.Configuration.RateLimiterOptions.SlidingWindow*
references:
- uid: RateLimiter.Configuration
  commentId: N:RateLimiter.Configuration
  href: RateLimiter.html
  name: RateLimiter.Configuration
  nameWithType: RateLimiter.Configuration
  fullName: RateLimiter.Configuration
  spec.csharp:
  - uid: RateLimiter
    name: RateLimiter
    href: RateLimiter.html
  - name: .
  - uid: RateLimiter.Configuration
    name: Configuration
    href: RateLimiter.Configuration.html
  spec.vb:
  - uid: RateLimiter
    name: RateLimiter
    href: RateLimiter.html
  - name: .
  - uid: RateLimiter.Configuration
    name: Configuration
    href: RateLimiter.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: RateLimiter.Configuration.RateLimiterOptions.TokenBucket*
  commentId: Overload:RateLimiter.Configuration.RateLimiterOptions.TokenBucket
  href: RateLimiter.Configuration.RateLimiterOptions.html#RateLimiter_Configuration_RateLimiterOptions_TokenBucket
  name: TokenBucket
  nameWithType: RateLimiterOptions.TokenBucket
  fullName: RateLimiter.Configuration.RateLimiterOptions.TokenBucket
- uid: RateLimiter.Configuration.TokenBucketOptions
  commentId: T:RateLimiter.Configuration.TokenBucketOptions
  parent: RateLimiter.Configuration
  href: RateLimiter.Configuration.TokenBucketOptions.html
  name: TokenBucketOptions
  nameWithType: TokenBucketOptions
  fullName: RateLimiter.Configuration.TokenBucketOptions
- uid: RateLimiter.Configuration.RateLimiterOptions.FixedWindow*
  commentId: Overload:RateLimiter.Configuration.RateLimiterOptions.FixedWindow
  href: RateLimiter.Configuration.RateLimiterOptions.html#RateLimiter_Configuration_RateLimiterOptions_FixedWindow
  name: FixedWindow
  nameWithType: RateLimiterOptions.FixedWindow
  fullName: RateLimiter.Configuration.RateLimiterOptions.FixedWindow
- uid: RateLimiter.Configuration.FixedWindowOptions
  commentId: T:RateLimiter.Configuration.FixedWindowOptions
  parent: RateLimiter.Configuration
  href: RateLimiter.Configuration.FixedWindowOptions.html
  name: FixedWindowOptions
  nameWithType: FixedWindowOptions
  fullName: RateLimiter.Configuration.FixedWindowOptions
- uid: RateLimiter.Configuration.RateLimiterOptions.SlidingWindow*
  commentId: Overload:RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
  href: RateLimiter.Configuration.RateLimiterOptions.html#RateLimiter_Configuration_RateLimiterOptions_SlidingWindow
  name: SlidingWindow
  nameWithType: RateLimiterOptions.SlidingWindow
  fullName: RateLimiter.Configuration.RateLimiterOptions.SlidingWindow
- uid: RateLimiter.Configuration.SlidingWindowOptions
  commentId: T:RateLimiter.Configuration.SlidingWindowOptions
  parent: RateLimiter.Configuration
  href: RateLimiter.Configuration.SlidingWindowOptions.html
  name: SlidingWindowOptions
  nameWithType: SlidingWindowOptions
  fullName: RateLimiter.Configuration.SlidingWindowOptions
